/** 英文→简体中文 技能名映射。自动生成于原站 en/zh-hans 语言包按官方表序对齐(research/align-skills.mjs)，请勿手改。 */
export const SKILL_NAME_EN_TO_ZH: Readonly<Record<string, string>> = {
  "Adaptability": "适应环境",
  "Adrenaline Rush": "巧击",
  "Agitator": "挑战者",
  "Airborne": "飞燕",
  "Alluring Pelt": "毛皮之诱惑",
  "Ambush": "急袭",
  "Antivirus": "无我之境",
  "Aquatic/Oilsilt Mobility": "适应水域·油泥",
  "Arkveld's Hunger": "锁刃龙之饥饿",
  "Artillery": "炮术",
  "Attack Boost": "攻击",
  "Ballistics": "弹道强化",
  "Bind Resistance": "束缚耐性",
  "Blangonga's Spirit": "雪狮子王之斗志",
  "Blast Attack": "爆破属性强化",
  "Blast Functionality": "爆破瓶追加",
  "Blast Resistance": "爆破异常耐性",
  "Bleeding Resistance": "裂伤耐性",
  "Blight Resistance": "属性异常耐性",
  "Blindsider": "闪光强化",
  "Blossomdance Prayer": "花舞祈祷",
  "Bludgeoner": "钝器能手",
  "Bombardier": "炸弹客",
  "Botanist": "植生学",
  "Burst": "连击",
  "Buttery Leathercraft": "皮革制品之顺滑",
  "Charge Master": "蓄力大师",
  "Charge Up": "蓄击强化",
  "Cliffhanger": "攀岩者",
  "Coalescence": "因祸得福",
  "Constitution": "体术",
  "Convert Element": "属性变换",
  "Counterstrike": "逆袭",
  "Critical Boost": "超会心",
  "Critical Draw": "拔刀术【技】",
  "Critical Element": "会心击【属性】",
  "Critical Eye": "看破",
  "Critical Status": "会心击【特殊】",
  "Defense Boost": "防御",
  "Divine Blessing": "精灵加护",
  "Doshaguma's Might": "辟兽之力",
  "Dragon Attack": "龙属性攻击强化",
  "Dragon Resistance": "龙耐性",
  "Dreamspell Prayer": "梦灯祈祷",
  "Earplugs": "耳塞",
  "Ebony Odogaron's Power": "凶爪龙之力",
  "Elemental Absorption": "属性吸收",
  "Entomologist": "昆虫标本达人",
  "Evade Extender": "回避距离提升",
  "Evade Window": "回避性能",
  "Exhaust Functionality": "减气瓶追加",
  "Festival Spirit": "祭典巡礼",
  "Fire Attack": "火属性攻击强化",
  "Fire Resistance": "火耐性",
  "Flamefete Prayer": "踊火祈祷",
  "Flayer": "锁刃刺击",
  "Flexible Leathercraft": "皮革制品之柔韧",
  "Flinch Free": "减轻胆怯",
  "Focus": "集中",
  "Foray": "攻势",
  "Fortifying Pelt": "毛皮之昂扬",
  "Free Meal": "满足感",
  "Fulgur Anjanath's Will": "雷颚龙之斗志",
  "Geologist": "地质学",
  "Glory's Favor": "荣光盛赞",
  "Gogmapocalypse": "巨戟龙的默示录",
  "Gore Magala's Tyranny": "黑蚀龙之力",
  "Gravios's Protection": "铠龙之守护",
  "Guard": "格挡性能",
  "Guard Up": "格挡强化",
  "Guardian Arkveld's Vitality": "护锁刃龙之命脉",
  "Guardian's Protection": "护龙之守护",
  "Guardian's Pulse": "护龙之脉动",
  "Handicraft": "匠",
  "Heroics": "火场怪力",
  "Horn Maestro": "吹笛名人",
  "Hunger Resistance": "饥饿耐性",
  "Ice Attack": "冰属性攻击强化",
  "Ice Resistance": "冰耐性",
  "Imparted Wisdom": "前辈之指引",
  "Intimidator": "威吓",
  "Iron Skin": "防御力下降耐性",
  "Item Prolonger": "道具使用强化",
  "Jin Dahaad's Revolt": "冻峰龙之反叛",
  "Jump Master": "跳跃铁人",
  "Latent Power": "力量解放",
  "Leap of Faith": "飞身跃入",
  "Leviathan's Fury": "海龙的涡雷",
  "Load Shells": "炮弹装填",
  "Lord's Favor": "霸主之骄傲",
  "Lord's Fury": "霸主之愤慨",
  "Lord's Soul": "霸主之魂",
  "Lumenhymn Prayer": "祝谣祈祷",
  "LV1 Slot Skill": "Lv1插槽 技能",
  "LV2 Slot Skill": "Lv2插槽 技能",
  "LV3 Slot Skill": "Lv3插槽 技能",
  "Marathon Runner": "跑者",
  "Master's Touch": "达人艺",
  "Maximum Might": "精神抖擞",
  "Mind's Eye": "心眼",
  "Mizutsune's Prowess": "泡狐龙之力",
  "Mushroomancer": "最爱蘑菇",
  "Neopteron Alert": "甲虫之直觉",
  "Neopteron Camouflage": "甲虫之拟态",
  "Normal Shots": "通常弹·通常箭强化",
  "Nu Udra's Mutiny": "狱焰蛸之反叛",
  "Offensive Guard": "攻击守势",
  "Omega Resonance": "欧米茄共鸣",
  "Opening Shot": "首发迅击",
  "Outdoorsman": "猎人生活",
  "Palico Rally": "指示随从",
  "Para Functionality": "麻痹瓶追加",
  "Paralysis Attack": "麻痹属性强化",
  "Paralysis Resistance": "麻痹耐性",
  "Partbreaker": "破坏王",
  "Peak Performance": "无伤",
  "Piercing Shots": "贯穿弹·龙之箭强化",
  "Poison Attack": "毒属性强化",
  "Poison Duration Up": "毒伤害强化",
  "Poison Functionality": "毒瓶追加",
  "Poison Resistance": "毒耐性",
  "Power Prolonger": "强化持续",
  "Protective Polish": "刚刃打磨",
  "Punishing Draw": "拔刀术【力】",
  "Quick Sheathe": "纳刀术",
  "Rapid Fire Up": "速射强化",
  "Rapid Morph": "高速变形",
  "Rathalos's Flare": "火龙之力",
  "Razor Sharp": "利刃",
  "Recovery Speed": "回复速度",
  "Recovery Up": "体力回复量提升",
  "Resentment": "怨恨",
  "Rey Dau's Voltage": "煌雷龙之力",
  "Scale Layering": "叠鳞之工艺",
  "Scaling Prowess": "铺鳞之技法",
  "Self-Improvement": "钻研",
  "Seregios's Tenacity": "千刃龙的斗志",
  "Shock Absorber": "缓冲",
  "Sleep Attack": "睡眠属性强化",
  "Sleep Functionality": "睡眠瓶追加",
  "Sleep Resistance": "睡眠耐性",
  "Slugger": "击晕术",
  "Soul of the Dark Knight": "暗黑骑士之证",
  "Special Ammo Boost": "特殊射击强化",
  "Speed Eating": "快吃",
  "Speed Sharpening": "砥石使用高速化",
  "Spread/Power Shots": "散弹·刚射强化",
  "Stamina Surge": "耐力急速回复",
  "Stamina Thief": "夺取耐力",
  "Stench Resistance": "恶臭耐性",
  "Stun Resistance": "昏厥耐性",
  "Survival Expert": "环境利用知识",
  "Tetrad Shot": "强四射击",
  "Thunder Attack": "雷属性攻击强化",
  "Thunder Resistance": "雷耐性",
  "Tool Specialist": "整备",
  "Tremor Resistance": "耐震",
  "Uth Duna's Cover": "波衣龙之守护",
  "Water Attack": "水属性攻击强化",
  "Water Resistance": "水耐性",
  "Weakness Exploit": "弱点特效",
  "Wide-Range": "广域化",
  "Windproof": "风压耐性",
  "Xu Wu's Vigor": "暗器蛸之力",
  "Zoh Shia's Pulse": "白炽龙之脉动",
};
